<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>GYM_System</RootNamespace>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="SavedPlans\**" />
	  <Content Remove="SavedPlans\**" />
	  <EmbeddedResource Remove="SavedPlans\**" />
	  <None Remove="SavedPlans\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="libwkhtmltox.dll" />
	  <None Remove="PdfTools\wkhtmltopdf.exe" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="PdfTools\wkhtmltopdf.exe">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
		<PackageReference Include="Google.Apis.Sheets.v4" Version="1.72.0.3966" />
		<PackageReference Include="Microsoft.Playwright" Version="1.59.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="QRCoder" Version="1.7.0" />
		<PackageReference Include="QuestPDF" Version="2025.12.4" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\images\fooditems\" />
		<Folder Include="wwwroot\images\exercises\" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="PdfTools\wkhtmltox.exe">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
	
</Project>
